import { useNavigate } from 'react-router-dom';
import { ArrowLeft, RefreshCw } from 'lucide-react';
import { useBriefStore } from '../store/brief.store';
import { useSessionStore } from '../store/session.store';
import { useIntakeStore } from '../store/intake.store';
import { BriefHeader } from '../components/brief/BriefHeader';
import { CCSection } from '../components/brief/CCSection';
import { HPISection } from '../components/brief/HPISection';
import { ROSSection } from '../components/brief/ROSSection';
import { PMHSection } from '../components/brief/PMHSection';
import { FlagsSection } from '../components/brief/FlagsSection';
import { DataQuality } from '../components/brief/DataQuality';
import { PDFExport } from '../components/brief/PDFExport';
import { Button } from '../components/shared/Button';
import { Spinner } from '../components/shared/Spinner';

export function BriefPage() {
  const navigate = useNavigate();
  const { brief, isGenerating, error } = useBriefStore();
  const { sessionInfo, reset: resetSession } = useSessionStore();
  const { turnCount, reset: resetIntake } = useIntakeStore();

  function handleNewIntake() {
    resetSession();
    resetIntake();
    useBriefStore.getState().reset();
    navigate('/');
  }

  if (isGenerating) {
    return (
      <div className="min-h-screen bg-[#F0FAF4] flex items-center justify-center">
        <div className="text-center">
          <Spinner size="lg" className="text-[#1B6B3A] mx-auto mb-4" />
          <p className="text-[#3D6B50] font-semibold">Generating Clinical Brief…</p>
          <p className="text-xs text-[#7A9E87] mt-1">Synthesizing {turnCount} turns of interview data</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-[#F0FAF4] flex items-center justify-center">
        <div className="text-center max-w-md">
          <p className="text-[#991B1B] font-semibold mb-2">Failed to generate brief</p>
          <p className="text-sm text-[#7A9E87] mb-4">{error}</p>
          <Button variant="secondary" onClick={() => navigate('/interview')}>
            <ArrowLeft className="w-4 h-4" /> Back to Interview
          </Button>
        </div>
      </div>
    );
  }

  if (!brief) {
    navigate('/');
    return null;
  }

  return (
    <div className="min-h-screen bg-[#F0FAF4] py-8 px-4">
      <div className="max-w-2xl mx-auto">
        {/* Nav */}
        <div className="flex items-center justify-between mb-6">
          <button onClick={() => navigate('/interview')} className="flex items-center gap-1.5 text-sm text-[#7A9E87] hover:text-[#1B6B3A] transition-colors">
            <ArrowLeft className="w-4 h-4" /> Back to Interview
          </button>
          <div className="flex items-center gap-2">
            <Button variant="secondary" size="sm" onClick={handleNewIntake}>
              <RefreshCw className="w-3.5 h-3.5" /> New Intake
            </Button>
            <PDFExport
              brief={brief}
              patientName={sessionInfo?.patientName ?? 'Patient'}
              patientAge={sessionInfo?.patientAge ?? 0}
              patientSex={sessionInfo?.patientSex ?? 'male'}
            />
          </div>
        </div>

        {/* Brief content */}
        <BriefHeader
          patientName={sessionInfo?.patientName ?? 'Patient'}
          patientAge={sessionInfo?.patientAge ?? 0}
          patientSex={sessionInfo?.patientSex ?? 'male'}
          generatedAt={brief.generatedAt}
          turnCount={turnCount}
        />

        <CCSection chiefComplaint={brief.chiefComplaint} />
        <HPISection hpi={brief.hpi} />
        <ROSSection ros={brief.ros} />
        <PMHSection
          pmh={brief.pmh}
          medications={brief.medications}
          allergies={brief.allergies}
          familyHistory={brief.familyHistory}
          socialHistory={brief.socialHistory}
        />
        <FlagsSection flags={brief.clinicalFlags} />
        <DataQuality notes={brief.dataQualityNotes} />

        <p className="text-center text-xs text-[#7A9E87] mt-6 pb-4">
          Generated by ClinIntake AI — Not a substitute for clinical judgment
        </p>
      </div>
    </div>
  );
}
