import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ClinicalBrief, ROS_SYSTEMS, ROS_LABELS } from '../types/clinical.types';
import { formatDate } from './clinical.utils';

const COLORS = {
  primary: [27, 107, 58] as [number, number, number],
  text: [13, 40, 24] as [number, number, number],
  muted: [122, 158, 135] as [number, number, number],
  alert: [153, 27, 27] as [number, number, number],
  lightGreen: [232, 245, 238] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
};

export function generateClinicalBriefPDF(
  brief: ClinicalBrief,
  patientName: string,
  patientAge: number,
  patientSex: 'male' | 'female'
): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  function addPageIfNeeded(spaceNeeded = 20): void {
    if (y + spaceNeeded > pageH - 25) {
      doc.addPage();
      y = margin;
      addPageFooter();
    }
  }

  function addPageFooter(): void {
    const footerY = pageH - 12;
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text('Generated by ClinIntake AI — Not a substitute for clinical judgment', margin, footerY);
    doc.text(
      `Page ${doc.getNumberOfPages()}`,
      pageW - margin,
      footerY,
      { align: 'right' }
    );
  }

  function sectionHeader(title: string): void {
    addPageIfNeeded(14);
    doc.setFillColor(...COLORS.lightGreen);
    doc.rect(margin, y, contentW, 8, 'F');
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.primary);
    doc.text(title, margin + 3, y + 5.5);
    y += 11;
  }

  function bodyText(text: string, indent = 0): void {
    const lines = doc.splitTextToSize(text, contentW - indent);
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.text);
    for (const line of lines) {
      addPageIfNeeded(6);
      doc.text(line, margin + indent, y);
      y += 5.5;
    }
    y += 2;
  }

  // --- HEADER ---
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageW, 32, 'F');

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('ClinIntake', margin, 13);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Pre-Visit Clinical Brief', margin, 20);

  doc.setFontSize(8);
  doc.setTextColor(200, 230, 212);
  doc.text('CONFIDENTIAL — FOR CLINICAL USE ONLY', pageW - margin, 20, { align: 'right' });

  y = 38;

  // Patient info band
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.text);
  doc.text(patientName, margin, y);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.muted);
  doc.text(`${patientAge}yo ${patientSex === 'male' ? 'Male' : 'Female'}  |  Date: ${formatDate(brief.generatedAt)}`, margin, y + 6);
  y += 16;

  // --- CC ---
  sectionHeader('CHIEF COMPLAINT (CC)');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bolditalic');
  doc.setTextColor(...COLORS.text);
  const ccLines = doc.splitTextToSize(`"${brief.chiefComplaint}"`, contentW - 6);
  for (const line of ccLines) {
    addPageIfNeeded(6);
    doc.text(line, margin + 3, y);
    y += 6;
  }
  y += 3;

  // --- HPI ---
  sectionHeader('HISTORY OF PRESENT ILLNESS (HPI)');
  bodyText(brief.hpi);

  // --- ROS ---
  sectionHeader('REVIEW OF SYSTEMS (ROS)');
  const rosRows = ROS_SYSTEMS.map((s) => [ROS_LABELS[s], brief.ros[s] ?? 'Not reviewed']);
  addPageIfNeeded(10);
  autoTable(doc, {
    startY: y,
    head: [['System', 'Findings']],
    body: rosRows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: COLORS.lightGreen },
    columnStyles: { 0: { cellWidth: 42, fontStyle: 'bold' } },
    didDrawPage: () => { addPageFooter(); },
  });
  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

  // --- PMH ---
  sectionHeader('PAST MEDICAL & SOCIAL HISTORY');
  addPageIfNeeded(10);
  autoTable(doc, {
    startY: y,
    head: [['Conditions', 'Medications', 'Allergies']],
    body: [[brief.pmh, brief.medications, brief.allergies]],
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontStyle: 'bold' },
    didDrawPage: () => { addPageFooter(); },
  });
  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  bodyText(`Family History: ${brief.familyHistory}`);
  bodyText(`Social History: ${brief.socialHistory}`);

  // --- CLINICAL FLAGS ---
  if (brief.clinicalFlags.length > 0) {
    sectionHeader('CLINICAL FLAGS');
    doc.setFillColor(254, 242, 242);
    const flagsHeight = brief.clinicalFlags.length * 6 + 8;
    addPageIfNeeded(flagsHeight);
    doc.rect(margin, y - 2, contentW, flagsHeight, 'F');
    doc.setDrawColor(...COLORS.alert);
    doc.setLineWidth(0.8);
    doc.line(margin, y - 2, margin, y - 2 + flagsHeight);
    for (const flag of brief.clinicalFlags) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.alert);
      doc.text(`• ${flag}`, margin + 4, y + 4);
      y += 6;
    }
    y += 6;
  }

  // --- DATA QUALITY NOTES ---
  sectionHeader('DATA QUALITY NOTES');
  bodyText(brief.dataQualityNotes);

  addPageFooter();

  const filename = `ClinIntake_${patientName.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
